### PR TITLE
Added Lw4

### PR DESCRIPTION
**Pull request by RylkovKirill**
https://anki-9bd54.web.app/#/home
login: test.user@gmail.com
password: 123456

### CODE REVIEW

**Review by gmltA — COMMENTED** [review]
Okay, I can offer you <kbd>8</kbd>. Is that enough?

**Comment by RylkovKirill** [comment]
I think yes.

**Comment by RylkovKirill** [comment]
If all theme requirements are met then in lab 5 i just need to add CI?

**Comment by gmltA** [comment]
> If all theme requirements are met then in lab 5 i just need to add CI?

That's right.

**Review by gmltA — APPROVED** [review]

**Pull request merged**
